config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'application#home'
  get    '/signup',  to: 'users#new'
  get     '/login',  to: 'sessions#new'
  post    '/login',  to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/events',  to: 'events#new'
  resources :users
  resources :events, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :attendances
  has_many :attendees, through: :attendances, source: "user"

  scope :past, -> { where("date < ?", DateTime.now) }
  scope :future, -> { where("date > ?", DateTime.now) }

  validates :title, presence: true, length: { maximum: 36 }
  validates :info, length: { maximum: 36 }
  validates :location, presence: true, length: { maximum: 36 }
  validates :date, presence: true
  validates :creator_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :events, class_name: 'Event', foreign_key: 'creator_id', dependent: :delete_all
    has_many :attendances
    has_many :events_as_attendee, through: :attendances, source: "event"
  
    validates :name, presence: true, length: { maximum: 24 },
              uniqueness: { case_sensitive: false }
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def home
  end
  private

    # Before filters

    # Confirms and filters a logged-in user.
    def logged_in_user
      if logged_in?
        redirect_to(user_path(@current_user)) if params[:id] != @current_user.id.to_s
      else
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in, only: [:new]

  def new
    @event = Event.new
    @users = User.where.not(id: @current_user.id)
  end

  def create
    @users = User.where.not(id: current_user.id)
    @event = Event.new(creator_id: session[:user_id], title: event_params[:title],
                       info: event_params[:info], location: event_params[:location],
                       date: event_params[:date])
    @event.valid? # create @event errors before test attendance_params
    if attendance_params != ['0'] && @event.save
      attendance_params[0..-2].each do |e| # create attendances
        Attendance.create(event_id: @event.id, user_id: e.to_i)
      end
      flash[:info] = "Event created!"
      redirect_to user_path(current_user)
    else
      @event.errors.messages[:attendees] = ["can't be none"] if attendance_params == ['0']
      render 'new'
    end
  end

  private

    def event_params
      params.require(:event).permit(:title, :info, :location, :date)
    end

    def attendance_params
      params.require(:attendees)
    end

    def logged_in
      if logged_in? == false
        flash[:danger] = "Please log in."
        redirect_to(login_path)
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user
      log_in @user
      redirect_back_or @user
    else
      flash.now[:danger] = 'Invalid name'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]

  def index
    @users = User.all
  end

  def show
    @user = @current_user
    @events_created_future = @user.events.future.order(date: :desc)
    @events_created_past = @user.events.past.order(date: :desc)
    @events_invited = Event.joins(:attendances).where(attendances:
                                    {'user_id' => current_user.id})
    @events_invited_future = @events_invited.future.order(date: :desc)
    @events_invited_past = @events_invited.past.order(date: :desc)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:info] = "Account creation successful!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    # Returns the full title on a per-page basis.
    def full_title(page_title = '')
      base_title = "Private Parties"
      if page_title.empty?
        base_title
      else
        page_title + " | " + base_title
      end
    end
  end
  

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    # Logs in the given user.
    def log_in(user)
      session[:user_id] = user.id
    end
  
    # Returns the current logged-in user (if any).
    def current_user
      if session[:user_id]
        @current_user ||= User.find_by(id: session[:user_id])
      end
    end
  
    # Returns true if the user is logged in, false otherwise.
    def logged_in?
      !current_user.nil?
    end
  
    # Logs out the current user.
    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
  
    # Redirects to stored location (or to the default).
    def redirect_back_or(default)
      redirect_to(session[:forwarding_url] || default)
      session.delete(:forwarding_url)
    end
  
    # Stores the URL trying to be accessed.
    def store_location
      session[:forwarding_url] = request.original_url if request.get?
    end
  end
  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<% provide(:title, 'Home') %>
<div class="box">
  <div class="big_container">
    <h1>Private Parties!</h1>
    <h2>A Rails events creator.</h2>
    
      <%= render 'shared/demo_message', size: 'p_small', link_on: true %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<h4>Create event</h4>
<% provide(:title, 'Create event') %>
<% provide(:button_text, 'Create my new event') %>
<%= form_for(@event) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="left_box" style="width:60%;">
    <%= f.label :title, style: "margin-left:40%" %>
    <%= f.text_field :title, class: 'form-control', style: "width:50%;margin-left:40%" %>
    <%= f.label :info, style: "margin-left:40%" %>
    <%= f.text_field :info, class: 'form-control', style: "width:50%;margin-left:40%" %>
    <%= f.label :location, style: "margin-left:40%" %>
    <%= f.text_field :location, class: 'form-control', style: "width:50%;margin-left:40%" %>
    <%= f.label :date, style: "margin-left:53%" %>
    <%= f.date_field :date, class: 'form-control', style: "width:25%;margin-left:53%" %>
    <%= f.submit yield(:button_text), class: "btn btn-primary", style: "width:40%;margin-left:45%" %>
  </div>
  <div class="right_box" style="width:40%;">
    <%= f.label 'invite friends' %>
    <% @users.each do |user| %>
      <div id="row">
        <div id="check_cell">
          <%= check_box_tag 'attendees[]', user.id %>
        </div>
        <div id="name_cell">
          <h5><%= user.name %></h5>
        </div>
      </div>
    <% end %>
    <%= hidden_field_tag 'attendees[]', '0' %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Private Parties", root_path, id: "logo" %>
    <% if logged_in? %>
      <%= link_to current_user.name, user_path(current_user), id: "name" %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Friends", users_path %></li>
          <li><%= link_to "Events", user_path(current_user) %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_demo_message.html.erb
<% id = size %>

<p style="text-align:right;">Azdren and Milos, 2019</p>

app/views/users/_event.html.erb
<% time == 'future' ? background = '#fcebff;' : background = '#e2bbf9;' %>
<div class="event_box" style="background-color:<%= background %>">
  <% if from.present? %>
    <h5 id="from">from: <%= event.creator.name %></h5>
    <hr></hr>
  <% end %>
  <h2 style="margin-bottom:15px;"><%= event.title %></h2>
  <h5><%= event.info %></h5>
  <h5><%= event.location %></h5>
  <h5 style="margin-bottom:15px;"><%= event.date.strftime("%A, %d %B, %Y") %></h5>
  <hr></hr>
  <h5 style="margin-top:-8px;">invited:</h5>
  <% event.attendees.each do |a| %>
    <h5><%= a.name %></h5>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/index.html.erb
<div class="stretch_box">
  <div class="big_container">
    <div class="left_box">
      <% if logged_in? %>
        <% provide(:title, 'Friends') %>
        <h1 style="float:left;margin-left:36px;">Friends</h1>
      <% else %>
        <% provide(:title, 'Users') %>
        <h1 style="float:left;margin-left:36px;">Users</h1>
      <% end %>
        <ul style="list-style:none;"><h3>
          <% @users.each do |user| %>
            <% unless user == current_user && logged_in? %>
              <%= content_tag(:li, user.name, style: "margin-top:2%;") %>
            <% end %>
          <% end %>
        </h3></ul>
    </div>
    <div class="right_box">
      <%= render 'shared/demo_message', size: 'p_large', link_on: false %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div style="margin:7%;"></div>
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h4>Sign up</h4>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>
<div class="stretch_box">
  <div class="big_container">
    <%= render 'shared/demo_message', size: 'p_large', link_on: true %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'My Events') %>
<div>
  <%= button_to 'Create new event', new_event_path, class: "btn btn-primary", style: "width:30%;margin:2% 35%", method: :get %>
</div>
<div class="left_box">
  <h3 style="text-align:center;">My events:</h3>
  <% if @events_created_future.empty? && @events_created_past.empty? %>
    <%= content_tag(:h5, 'no events created.', class: "shadow", style: "text-align:center;") %>
  <% end %>
  <% unless @events_created_future.empty? %>
    <%= content_tag(:h5, 'future:', class: "shadow", style: "text-align:center;") %>
  <% end %>
  <% @events_created_future.each do |event| %>
    <%= render 'event', event: event, time: 'future', from: '' %>
  <% end %>
  <% unless @events_created_past.empty? %>
    <%= content_tag(:h5, 'past:', class: "shadow", style: "text-align:center;") %>
  <% end %>
  <% @events_created_past.each do |event| %>
    <%= render 'event', event: event, time: 'past', from: '' %>
  <% end %>
</div>
<div class="right_box">
  <h3 style="text-align:center;">Invitations:</h3>
  <% if @events_invited_future.empty? && @events_invited_past.empty? %>
    <%= content_tag(:h5, 'no invitations received.', class: "shadow", style: "text-align:center;") %>
  <% end %>
  <% unless @events_invited_future.empty? %>
    <%= content_tag(:h5, 'future:', class: "shadow", style: "text-align:center;") %>
  <% end %>
  <% @events_invited_future.each do |event| %>
    <%= render 'event', event: event, time: 'future', from: @user.name %>
  <% end %>
  <% unless @events_invited_past.empty? %>
    <%= content_tag(:h5, 'past:', class: "shadow", style: "text-align:center;") %>
  <% end %>
  <% @events_invited_past.each do |event| %>
    <%= render 'event', event: event, time: 'past', from: @user.name %>
  <% end %>
</div>